file = open('input.txt', 'w')
file.write('Hello, world!')
file.close()
input=open("input.txt",'r')
content=input.read()
input.close()
output=open("outout.txt",'w')
output.write(content)
output.close()
print(output)